### ISSUE TITLE
OKX 钱包打的到不了帐

### ISSUE THREAD

**Issue by eliiik** [VedaOrg/Veda-core#1]

**Comment by Raylin51** [comment]
ok钱包的公钥不是一个标准的压缩公钥，它提供的公钥少了公钥开头的奇偶性验证，当前版本验证不了这种非标准的压缩公钥，会在后续块高升级来支持这个非标准的验证

**Comment by eliiik** [comment]
> ok钱包的公钥不是一个标准的压缩公钥，它提供的公钥少了公钥开头的奇偶性验证，当前版本验证不了这种非标准的压缩公钥，会在后续块高升级来支持这个非标准的验证

后续会把之前用 OKX 钱包打的 veda 计入余额吗

**Comment by Raylin51** [comment]
之前的已经执行过的结果不会有任何更改，需要保证数据的一致性和唯一性
